
WHITESPACE = _{ " " | "\t" | "\\" | NEWLINE}

Variable = @{ "_" | (ASCII_ALPHA ~ ( "_" | ASCII_ALPHANUMERIC )*) }

Lhs = { Variable }

Operator = { "+" | "-" | "*" | "/" | "^"  }

Parenthetical = { "(" ~ Expression ~ ")" }

Negation = { "-" ~ Expression }

Literal  = @{ ASCII_DIGIT+ }

Value = { Variable | Literal | Parenthetical }

Expression = { Negation | (Value ~ (Operator ~ Value)*) }

Main = { SOI ~ ( Lhs ~ "=" )? ~ Expression ~ EOI }
